/**
 * Discord notification module exports
 */

// Types
export {
  DiscordEmbedColor,
  DiscordMessageStatus,
  type DiscordWebhookConfig,
  type DiscordEmbedFooter,
  type DiscordEmbedImage,
  type DiscordEmbedThumbnail,
  type DiscordEmbedAuthor,
  type DiscordEmbedField,
  type DiscordEmbed,
  type DiscordMessage,
  type DiscordAllowedMentions,
  type DiscordSendResult,
  type DiscordRateLimitInfo,
  type DiscordEventType,
  type DiscordEvent,
  type DiscordEventHandler,
  type DiscordBatchOptions,
  type DiscordBatchResult,
  type DiscordWebhookInfo,
  // Validation functions
  isValidWebhookUrl,
  extractWebhookId,
  maskWebhookUrl,
  isValidFieldValue,
  isValidFieldName,
  isValidEmbedTitle,
  isValidEmbedDescription,
  isValidMessageContent,
  calculateEmbedCharacterCount,
  isValidEmbedTotal,
  truncateForDiscord,
  formatTimestampForEmbed,
  generateResultId,
} from "./types";

// Client
export {
  DiscordClient,
  DiscordClientError,
  getDiscordClient,
  createDiscordClient,
  resetDiscordClient,
} from "./client";

// Embed Formatter
export {
  type AlertSeverity,
  type AlertType,
  type DiscordAlertData,
  type DiscordAlertOptions,
  type FormattedDiscordEmbed,
  type AlertTypeConfig,
  type SeverityConfig,
  ALERT_TYPE_CONFIG,
  SEVERITY_CONFIG,
  formatCurrency,
  formatPercentage,
  truncateWallet,
  getAlertColor,
  createEmbedField,
  createAlertFields,
  buildAlertEmbed,
  formatDiscordAlert,
  createAlertMessage,
  createAlertEmbeds,
  createAlertSummaryEmbed,
  createAlertSummaryMessage,
  getSeverityEmoji,
  getSeverityColor,
  getAlertTypeEmoji,
  getAlertTypeLabel,
  getAlertTypeColor,
  validateAlertData,
  createSimpleEmbed,
  createErrorEmbed,
  createSuccessEmbed,
  createInfoEmbed,
  createWarningEmbed,
} from "./embed-formatter";
