/**
 * Telegram Bot Module
 *
 * Exports the Telegram bot client and related utilities.
 */

export {
  TelegramBotClient,
  getTelegramBot,
  createTelegramBot,
  startTelegramBot,
  stopTelegramBot,
  type BotStatus,
  type BotInitResult,
  type Bot,
  type Context,
} from "./bot";

export {
  handleStartCommand,
  createStartCommandHandler,
  registerUserFromContext,
  getWelcomeMessage,
  handleMyChatMember,
  createMyChatMemberHandler,
  getGroupWelcomeMessage,
  getGroupFarewellMessage,
  isBotMember,
  isBotRemoved,
  handleStopCommand,
  createStopCommandHandler,
  unsubscribeUser,
  getUnsubscribeMessage,
  getAlreadyUnsubscribedMessage,
  getNotFoundMessage,
  // Settings command exports
  handleSettingsCommand,
  createSettingsCommandHandler,
  handleSettingsCallback,
  createSettingsCallbackHandler,
  getAlertPreferences,
  updatePreferenceFromCallback,
  parseSettingsCallback,
  getSettingsKeyboard,
  getMinTradeSizeKeyboard,
  getSeverityKeyboard,
  getSettingsMessage,
  formatPreferenceValue,
  getFieldDisplayName,
  isSettingsCallback,
  MIN_TRADE_SIZE_OPTIONS,
  SEVERITY_OPTIONS,
  CALLBACK_PREFIX,
  // Help command exports
  handleHelpCommand,
  createHelpCommandHandler,
  getHelpMessage,
  // Status command exports
  handleStatusCommand,
  createStatusCommandHandler,
  getSubscriptionStatus,
  getStatusMessage,
  formatDate,
  escapeMarkdown,
  // Stats command exports (admin only)
  handleStatsCommand,
  createStatsCommandHandler,
  checkIsAdmin,
  getUnauthorizedMessage,
  getStatsMessage,
  getUptimeString,
  // Broadcast command exports (admin only)
  handleBroadcastCommand,
  createBroadcastCommandHandler,
  broadcastMessage,
  parseBroadcastMessage,
  getBroadcastReportMessage,
  getEmptyBroadcastMessage,
  // Test command exports (admin only)
  handleTestCommand,
  createTestCommandHandler,
  getTestAlertMessage,
  type RegistrationResult,
  type GroupMembershipResult,
  type UnsubscribeResult,
  type SettingsResult,
  type PreferenceUpdateResult,
  type StatusResult,
  type AdminCheckResult,
  type BotStats,
  type AdminBroadcastResult,
  type TestAlertResult,
} from "./commands";

// Broadcaster exports
export {
  AlertBroadcaster,
  alertBroadcaster,
  createAlertBroadcaster,
  broadcastAlert,
  sendAlertToSubscriber,
  formatAlertMessage,
  formatAlertType,
  formatNumber,
  formatTimestamp,
  escapeMarkdown as escapeMarkdownBroadcast,
  getSeverityEmoji,
  getAlertTypeEmoji,
  matchesAlertPreferences,
  filterEligibleSubscribers,
  meetsSeverityRequirement,
  shouldDeactivateOnError,
  logDeactivation,
  // Cleanup service exports
  SubscriberCleanupService,
  subscriberCleanupService,
  createSubscriberCleanupService,
  type SendResult,
  type BroadcastResult,
  type BroadcastOptions,
  type DeactivationReasonType,
  type DeactivationInfo,
  type CleanupConfig,
  type CleanupResult,
} from "./broadcaster";
